# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
print(mongo.list_database_names())

['admin', 'autosaurus', 'classDB', 'config', 'epaDB', 'fruits_db', 'local', 'met', 'travel_db', 'uk_food']

In [4]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [5]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [6]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [7]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene':20}
query

{'scores.Hygiene': 20}

In [8]:
# Use count_documents to display the number of documents in the result
result_count = establishments.count_documents(query)
print(result_count)

41

In [9]:
#Display the first document in the results using pprint
results = list(establishments.find(query))
pprint(results[0])

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0.0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6590a30289569805644e4084'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'latitude': 50.769705,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': 0.27694,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [10]:
# Convert the result to a Pandas DataFrame
result_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Rows in DataFrame: ", len(result_df))

# Display the first 10 rows of the DataFrame
result_df.head(10)

Rows in DataFrame:  41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,6590a30289569805644e4084,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",0.276940,50.769705
1,6590a30289569805644e4405,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",1.278721,51.857536
2,6590a30289569805644e470f,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",1.159270,51.789429
3,6590a30289569805644e48fd,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",0.102020,50.770885
4,6590a30289569805644e490c,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",0.101446,50.770724
5,6590a30489569805644e52ab,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",0.736349,51.541448
6,6590a30489569805644e54cc,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",0.712167,51.535007
7,6590a30789569805644e69f7,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.602364,51.591515
8,6590a30789569805644e6e3b,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.146450,51.185947
9,6590a30889569805644e764d,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.462307,51.570050

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [11]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"RatingValue": {"$gte": 4}, "AddressLine4":"London"}

# Use count_documents to display the number of documents in the result
result_count = establishments.count_documents(query)
print("Number of documents in result:", result_count)

# Display the first document in the results using pprint
results = list(establishments.find(query))
pprint(results[0])

Number of documents in result: 390
{'AddressLine1': 'Arch D',
 'AddressLine2': 'The Link Thamesmead',
 'AddressLine3': 'Bazalgette Way',
 'AddressLine4': 'London',
 'BusinessName': 'The Mezzanine Cafe',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4646.357884390823,
 'FHRSID': 1049722,
 'LocalAuthorityBusinessID': '18/00096/CP',
 'LocalAuthorityCode': '503',
 'LocalAuthorityEmailAddress': 'food.safety@bexley.gov.uk',
 'LocalAuthorityName': 'Bexley',
 'LocalAuthorityWebSite': 'http://www.bexley.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE2 9BS',
 'RatingDate': '2022-05-24T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4.0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6590a30b89569805644e9536'),
 'geocode': {'latitude': 51.5002632141113, 'longitude': 0.121751002967358},
 'latitude': 51.5002632141113,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1049722',
            'rel': 'self'}],
 'longitude': 0.121751002967358,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 10, 'Hygiene': 10, 'Structural': 0}}

In [12]:
# Convert the result to a Pandas DataFrame
result_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Rows in DataFrame: ", len(result_df))

# Display the first 10 rows of the DataFrame
result_df.head(10)

Rows in DataFrame:  390

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,6590a30b89569805644e9536,1049722,0,18/00096/CP,The Mezzanine Cafe,Restaurant/Cafe/Canteen,1,Arch D,The Link Thamesmead,Bazalgette Way,...,"{'Hygiene': 10, 'Structural': 0, 'ConfidenceIn...",FHRS,"{'longitude': 0.121751002967358, 'latitude': 5...",,4646.357884,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.121751,51.500263
1,6590a30b89569805644e9557,1261451,0,20/00255/MIXED,"St Edward's Church, Mottingham - StEP Lunch Cl...",Other catering premises,7841,St Edwards Church Hall,St Keverne Road,Mottingham,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.04774, 'latitude': 51.428019}",,4646.410908,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.047740,51.428019
2,6590a30b89569805644e955c,987733,0,16/00340/MIXED,Maryfield Pre-School 2,Caring Premises,5,Mottingham Community Centre,Kimmeridge Road,Mottingham,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0465259999036789, 'latitude': ...",,4646.414831,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.046526,51.426914
3,6590a30b89569805644e955d,357627,0,00000/0000/8/951,Co-op,Retailers - supermarkets/hypermarkets,7840,The Co-operative Food,Kimmeridge Road,Mottingham,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0465259999036789, 'latitude': ...",,4646.414831,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.046526,51.426914
4,6590a30b89569805644e957a,1151706,0,00000/0000/8/204,North Hub @ Castlecombe Youth Centre,Caring Premises,5,Castlecombe Youth Centre,Castlecombe Road,Mottingham,...,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.0433179996907711, 'latitude': ...",,4646.439635,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.043318,51.424389
5,6590a30b89569805644e957e,1468037,0,22/00180/MIXED,Spencers,Retailers - other,4613,11 Cranley Parade,Kimmeridge Road,Mottingham,...,"{'Hygiene': 0, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.046141, 'latitude': 51.427318}",,4646.443677,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.046141,51.427318
6,6590a30b89569805644e957f,358232,0,02/00010/MIXED,Domino's Pizza,Takeaway/sandwich shop,7844,3 Cranley Parade,Beaconsfield Road,Mottingham,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.046141, 'latitude': 51.427318}",,4646.443677,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.046141,51.427318
7,6590a30b89569805644e9589,1415217,0,21/00630/MIXED,Papa John's Pizza,Takeaway/sandwich shop,7844,4 Cranley Parade,Beaconsfield Road,Mottingham,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0460971, 'latitude': 51.4273993}",,4646.448256,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.046097,51.427399
8,6590a30b89569805644e959c,635108,0,14/00056/MIXED,Perfect Cafe,Restaurant/Cafe/Canteen,1,11 Beaconsfield Parade,Beaconsfield Road,Mottingham,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.045445, 'latitude': 51.427186}",,4646.464277,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.045445,51.427186
9,6590a30b89569805644e959d,357579,0,00000/0000/8/062,Superfry Fish Bar,Takeaway/sandwich shop,7844,12 Beaconsfield Parade,Beaconsfield Road,Mottingham,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.045445, 'latitude': 51.427186}",,4646.464277,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",0.045445,51.427186

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [26]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.10
latitude = 0.08384
longitude = 51.490142

#Define the latitude and longitude range
latitude_range = [latitude - degree_search, latitude + degree_search]
longitude_range = [longitude - degree_search, longitude + degree_search]

match_query = {'$match': {'geocode.latitude': {'$gte': latitude_range[0], '$lte': latitude_range[1]},
        'geocode.longitude': {'$gte': longitude_range[0], '$lte': longitude_range[1]},
        "RatingValue":5}}

# Sort by max height in descending order
sort_query = {'$sort': {'scores.hygiene': -1}}

# Put the pipeline together
pipeline = [match_query, sort_query]

In [35]:
# Execute the query and limit the results to 5
results = list(establishments.aggregate(pipeline))
results

# # Print each document
# for result in results:
#     pprint(results)

[]

In [28]:
# Convert result to Pandas DataFrame
result_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Rows in DataFrame: ", len(result_df))

# Display the first 10 rows of the DataFrame
result_df.head(10)

Rows in DataFrame:  0

Empty DataFrame
Columns: []
Index: []

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [17]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest


# Match documents where scores.hygiene is equal to 0
match_query = {'$match': {'scores.hygiene': 0}}

# Group by "LocalAuthority" and find count and max height
group_query = {
    '$group': {
        '_id': '$LocalAuthority',  # Group by LocalAuthority
        'count': {'$sum': 1},      # Count documents in each group
        'maxHeight': {'$max': '$height'}  # Find max height in each group
    }
}

# Sort by max height in descending order
sort_query = {'$sort': {'maxHeight': -1}}

# Put the pipeline together
pipeline = [match_query, group_query, sort_query]

# Execute the aggregation pipeline
results = list(establishments.aggregate(pipeline))

# Print the results
pprint(results)

[]

In [18]:
# Convert result to Pandas DataFrame
result_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Rows in DataFrame: ", len(result_df))

# Display the first 10 rows of the DataFrame
result_df.head(10)

Rows in DataFrame:  0

Empty DataFrame
Columns: []
Index: []